version: "3.2"
services:
    mongodb_container:
        image: mongo:latest
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: rootpassword
        ports:
            - 27017:27017

    portalbackend:
        restart: always
        container_name: code
        command: bash -c "python manage.py migrate &&
                        python manage.py runserver 0.0.0.0:8000"
#        env_file:
#        - ./PortalBackend/PortalBackend/settings.py
        build:
            context: ./PortalBackend/
            dockerfile: Dockerfile
        ports:
        - "8000:8000"
        depends_on:
        - mongodb_container
        networks:
        - db-net

    portal:
        restart: always
        command : npm start
        container_name: front
        build:
            context: ./portal/
            dockerfile: Dockerfile
        ports:
        - "3000:3000"
        stdin_open: true
        depends_on:
        - portalbackend
        networks:
        - db-net

networks:
    db-net:
        driver: bridge