# Generated by Django 3.0.5 on 2020-10-26 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmodel',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='emailmodel',
            name='phoneNumber',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='emailmodel',
            name='zip',
            field=models.CharField(default='', max_length=5),
        ),
    ]
