# Generated by Django 3.0.5 on 2020-12-02 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailmodel',
            name='phoneNumber',
        ),
        migrations.AddField(
            model_name='emailmodel',
            name='address',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AddField(
            model_name='emailmodel',
            name='birthday',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AddField(
            model_name='emailmodel',
            name='currentTown',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AddField(
            model_name='emailmodel',
            name='hometown',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AddField(
            model_name='emailmodel',
            name='interests',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AddField(
            model_name='emailmodel',
            name='jobDetails',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AddField(
            model_name='emailmodel',
            name='password',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AddField(
            model_name='emailmodel',
            name='phoneNum',
            field=models.CharField(default='none', max_length=15),
        ),
        migrations.AddField(
            model_name='emailmodel',
            name='politicalViews',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AddField(
            model_name='emailmodel',
            name='relationshipStatus',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AddField(
            model_name='emailmodel',
            name='religiousViews',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AddField(
            model_name='emailmodel',
            name='ssn',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AlterField(
            model_name='emailmodel',
            name='email',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AlterField(
            model_name='emailmodel',
            name='name',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AlterField(
            model_name='emailmodel',
            name='zip',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
