# Generated by Django 3.0.5 on 2021-02-03 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_emailmodel_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmodel',
            name='dateCollected',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
